# Numpy Basics Exercises

Please complete the following exercises **using numpy only**.

# Array Broadcasting
NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are broadcasted to match the larger arrays, without copying data.

Broadcasting has two rules.

RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE

RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING

In [38]:
# Answer here
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

b = np.array([1, 2, 3, 4])
c=a+b
c

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [39]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

b = np.array([[1],
              [2],
              [3]])
a+b

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.


In [35]:
# Answer here
import numpy as np

a = np.array([1, 2, 3, 4])
result = np.add.reduce(a)
print(result)  # Output: 10

10


In [36]:
result = np.add.accumulate(a)
print(result)

[ 1  3  6 10]


### Create a 2-D array where the first row goes from 10 to 80 exclusive with steps of 5 and 2nd row goes from 5 to 47 exclusive with steps of 3

In [1]:
import numpy as np
a=np.arange(10,80,5)
b=np.arange(5,47,3)

c=np.array((a,b))
c

array([[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75],
       [ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44]])

### Now use indexing to select the 5th 7th and 11th columns

In [2]:
print(c[:,5])
print(c[:,7])
print(c[:,11])
c[:,[5,7,11]]

[35 20]
[45 26]
[65 38]


array([[35, 45, 65],
       [20, 26, 38]])

### Select the 2nd row and fourth-last to second-last columns

In [3]:

print(c[1,:])
print(c[[1],-4:-1])


[ 5  8 11 14 17 20 23 26 29 32 35 38 41 44]
[[35 38 41]]


### Select 3rd to 3rd last columns skipping every second column

In [4]:
print(c)

c[::,2:-3:2]

[[10 15 20 25 30 35 40 45 50 55 60 65 70 75]
 [ 5  8 11 14 17 20 23 26 29 32 35 38 41 44]]


array([[20, 30, 40, 50, 60],
       [11, 17, 23, 29, 35]])

###  Select 3rd to 3rd last columns skipping every second column but in reverse order

In [5]:
c[::,-3::2]

array([[65, 75],
       [38, 44]])

### We will work with the following array:

In [6]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
a[[1,2,3],[2,3,4]]

array([ 7, 13, 19])

### Use slicing only to select 3rd and last row along with 2nd and last columns

In [8]:
a[2::2,3:]

array([[13, 14],
       [23, 24]])

### Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]

In [9]:
print(a[0,2:4])
print(a[2,2:4])
print(a[4,2:4])
print(a)
a[[0,2,3],2:4]

[2 3]
[12 13]
[22 23]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 2,  3],
       [12, 13],
       [17, 18]])

### Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]

In [10]:

print(a[1:2,[1,3]])
print(a[3:4,[1,3]])
print(a[-1,[1,3]])

print(a)

a[[1,3,4],1::2]

[[6 8]]
[[16 18]]
[21 23]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 6,  8],
       [16, 18],
       [21, 23]])

### Change the values 1, 10, 19 and 22 in the array to -2

In [11]:
print(a)
a[[0,2,3,4],[1,0,-1,2]]=-2
a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 0, -2,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [-2, 11, 12, 13, 14],
       [15, 16, 17, 18, -2],
       [20, 21, -2, 23, 24]])

### Repeat above using boolean indexing

In [12]:
a[[0,2,3,4],[1,0,-1,2]]==-2

array([ True,  True,  True,  True])

In [13]:
a

array([[ 0, -2,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [-2, 11, 12, 13, 14],
       [15, 16, 17, 18, -2],
       [20, 21, -2, 23, 24]])

### Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]

In [14]:
mask = np.array([1,0,1,1,0],dtype='bool')
x=a[mask,:4:3]
x

array([[ 0,  3],
       [-2, 13],
       [15, 18]])

### Calculating the sum, min and max of all diagonal values

In [24]:
print(a)

print(np.diag(a).sum())
print(np.diag(a).min())
print(np.diag(a).max())

[[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 18 -2]
 [20 21 -2 23 24]]
60
0
24


### Calculate the sum of differences between the 2nd row and 2nd last column

In [30]:
print("sum of 2nd row is: ", a[1,:].sum())
print("sum of 2nd last col is: ", a[:,-2].sum())
print("Sum diff between 2nd row and 2nd last col is: ",a[:,-2].sum()-a[1,:].sum())

sum of 2nd row is:  35
sum of 2nd last col is:  65
Sum diff between 2nd row and 2nd last col is:  30


### Create a new array that is the sum of even rows and odd rows

In [34]:
print(a)
print("Sum of odd rows are: ",a[::2,:].sum())
print("Sum of even rows are: ",a[1::2,::].sum())

[[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 18 -2]
 [20 21 -2 23 24]]
Sum of odd rows are:  141
Sum of even rows are:  99


## You are done. Good job!