In [1]:
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Q.1
**Statement:** You are working with a retail store that needs to manage its inventory efficiently. They have provided you with a dataset containing information about products, their quantities in stock, and the number of units sold daily for the past week. Total number of products are 5. Your task is to calculate the following:



1.The total sales for each product over the past week.

2.The average daily sales for each product.

3.The product with the highest sales.

4.The product with the lowest sales.

5.The total sales for all products combined.

You are required to use NumPy for efficient data processing and calculations. Write code to solve this inventory management problem.

In [15]:
import numpy as np

# Sample data (replace with your actual data)
product_names = np.array(['Product A', 'Product B', 'Product C', 'Product D', 'Product E'])
quantities_in_stock = np.array([100, 150, 200, 250, 50])

daily_sales_data = np.array([[10, 15, 20, 25, 30, 35, 40],
                             [5, 7, 8, 10, 12, 14, 16],
                             [15, 20, 25, 30, 35, 40, 40],
                             [12, 25, 20, 40, 20, 32, 55],
                             [15, 20, 25, 30, 35, 40, 45]])

# Calculate total sales revenue for each product over the past week
revenue= np.array([[10,15,20,25,30]])
for i in range(len(product_names)):
    print(f"Total Sales Revenue of {product_names[i]} is: ",np.sum(daily_sales_data[i]))
    

print(np.sum(daily_sales_data,axis=1))

# Calculate average daily sales for each product
for i in range(len(product_names)):
    print(f"Average daily Sales of {product_names[i]} is: ",np.mean(daily_sales_data[i]))
#np.mean(daily_sales_data,axis=1)



# Find the product with the highest and lowest sales
print(np.max(daily_sales_data[i]),np.min(daily_sales_data))



# Calculate the total sales revenue for all products combined
np.sum(daily_sales_data)

Total Sales Revenue of Product A is:  175
Total Sales Revenue of Product B is:  72
Total Sales Revenue of Product C is:  205
Total Sales Revenue of Product D is:  204
Total Sales Revenue of Product E is:  210
[175  72 205 204 210]


AxisError: axis 1 is out of bounds for array of dimension 1

# Q.2
**Statement:** Statement: You are working with a manufacturing plant that produces various components. They have provided you with data on the production rates of five different machines over the past month. Your task is to analyze the performance of these machines by calculating the following metrics:

1.The total production output for each machine over the past month.

2.The average daily production rate for each machine.

3.The machine with the highest total production output.

4.The machine with the lowest total production output.

The overall production efficiency of the plant, which is defined as the ratio of the total production output to the total number of hours worked, and working hour for each day is 2 hours.

In [32]:


# Sample data (replace with your actual data)


# Generate random production rates between 100 and 200 for 5 machines and 30 days
data=np.random.randint(100,201,size=(5,30))
print(data)

# Calculate total production output for each machine over the past month
print(np.sum(data,axis=1))

# Calculate average daily production rate for each machine
print(np.mean(data,axis=1))

# Find the machine with the highest and lowest total production output
print(np.max(data))
print(np.min(data))
# Calculate the overall production efficiency of the plant
print(np.sum(data)/(5*2*30))


[[182 107 139 176 175 177 115 195 111 145 129 150 181 100 137 131 190 156
  124 172 114 156 108 103 115 117 100 191 199 166]
 [136 171 117 161 198 100 200 167 190 108 138 173 180 143 100 143 200 120
  177 111 149 162 196 129 125 199 156 179 115 170]
 [179 164 199 178 166 147 168 169 174 138 127 117 113 138 185 131 198 169
  172 183 177 175 156 108 164 132 151 168 166 151]
 [160 120 103 183 151 161 125 101 132 103 114 191 175 113 132 116 127 105
  170 188 199 177 161 197 107 183 138 116 127 114]
 [101 141 169 119 105 125 121 180 182 120 195 199 124 185 179 186 165 193
  183 157 118 194 154 168 107 199 150 146 181 143]]
[4361 4613 4763 4289 4689]
[145.36666667 153.76666667 158.76666667 142.96666667 156.3       ]
200
100
75.71666666666667


# Q3:

**Statment**
You are working on a project that involves simulating sensor data for a network of 10 sensors over a period of 15 days. Each sensor collects data once per hour. Your task is to generate a NumPy array named sensor_data to represent this simulated sensor data and perform following statistical analysis on it.

Populate the sensor_data array with random floating-point values between 0.0 and 100.0
The generated values should represent sensor readings collected once per hour.

After generating the sensor_data array, perform the following statistical **calculations:**

1.Calculate the mean (average) sensor reading for each sensor over the 15 days.

2.Calculate the standard deviation of sensor readings for each sensor.

3.Calculate the maximum sensor reading for each sensor.

4.Calculate the minimum sensor reading for each sensor.

5.Calculate the overall mean sensor reading for all sensors and all days.

6.Calculate the overall standard deviation of sensor readings for all sensors an

In [3]:
import numpy as np

# Data Generation Requirements
num_sensors = 10
num_days = 15
hours_per_day = 24
shape = (num_sensors, num_days * hours_per_day)

#Calculate the mean (average) sensor reading for each sensor over the 15 days.
data=np.random.randint(0.0,100.0,size=(10,15,24))
print(np.mean(data,axis=(1,2)))

#Calculate the standard deviation of sensor readings for each sensor.
print(np.std(data,axis=(1,2)))

#Calculate the maximum sensor reading for each sensor.
print(np.max(data,axis=(1,2)))

#Calculate the minimum sensor reading for each sensor.
print(np.min(data,axis=(1,2)))

#Calculate the overall mean sensor reading for all sensors and all days.
print(np.mean(data))

#Calculate the overall standard deviation of sensor readings for all sensors an
np.std(data)

[48.85833333 50.15555556 47.05       50.73611111 51.08055556 50.58888889
 53.68333333 50.53611111 51.83055556 52.88055556]
[30.12159501 27.38619324 28.28157527 30.07582688 27.09103295 29.7500306
 29.48077999 29.09971032 28.60024591 28.96079073]
[99 99 99 99 99 99 99 99 98 99]
[0 0 0 0 0 0 0 0 0 0]
50.74


28.957606177920773

# Q4:

**Statement**: You are tasked with analyzing the exam scores of 30 students in a class over a period of 10 exams. The exam scores are represented as a NumPy, where each row corresponds to a different student, and each column represents their score in a specific exam.

Populate the exam_scores array with random integer values between 50 and 100 to simulate students' exam performance.

After generating the exam_scores array, perform the following tasks:

1.Calculate the average score for each student over the 10 exams.

2.Calculate the standard deviation of scores for each student.

3.Identify students who have consistently performed well, defined as those whose average score is above 85.

4.Identify students who may need additional support, defined as those whose average score is below 50.

Write code to create and populate the exam_scores array and then perform the specified statistical analysis and performance evaluation tasks on the data.





In [11]:
import numpy as np

# Create the exam_scores array (30 students, 10 exams)
num_students = 30
num_exams = 10

# Populate the exam_scores array with random scores between 50 and 100
data=np.random.randint(50,100,size=(30,10))
print(data)

# 1. Calculate the average score for each student over the 10 exams
print(np.mean(data,axis=1))

# 2. Calculate the standard deviation of scores for each student
print(np.std(data,axis=1))


# 3. Identify students who have consistently performed well (average score > 85)
results=[]
index_no=0
for i in range(len(data)):
    if data[i].mean() >= 85:
        r1=results.append(data[i].mean())
    else:
        index_no +=1
print(results)
print(len(results))
print(index_no)
# 4. Identify students who may need additional support (average score < 60)

np.where(np.mean(data,axis=0))

[[68 78 71 82 84 67 54 52 73 64]
 [99 59 86 96 65 69 83 92 76 65]
 [75 96 53 56 65 91 84 67 99 59]
 [75 99 74 69 72 92 85 71 81 50]
 [58 62 84 93 77 93 89 69 59 82]
 [60 52 69 79 56 72 96 65 57 70]
 [87 74 93 81 57 51 72 72 68 85]
 [53 98 98 53 92 59 74 56 58 69]
 [78 71 55 67 97 65 79 95 89 68]
 [76 54 92 71 88 96 53 78 59 74]
 [98 82 57 93 57 94 84 67 91 53]
 [99 80 75 89 59 53 66 65 93 95]
 [54 63 76 76 52 87 51 67 81 68]
 [92 98 63 54 82 75 88 69 55 92]
 [81 50 99 79 81 51 68 77 93 90]
 [66 61 95 92 85 98 97 54 84 53]
 [78 82 86 69 63 68 96 96 60 89]
 [96 91 66 96 86 78 71 81 94 95]
 [99 61 74 83 81 69 75 69 97 98]
 [54 75 67 76 89 82 78 89 82 85]
 [89 77 62 68 74 92 72 75 80 85]
 [63 90 93 87 77 56 71 51 84 94]
 [76 67 51 83 75 54 98 90 80 70]
 [91 70 91 68 57 93 81 70 88 61]
 [71 65 54 55 94 72 91 69 97 58]
 [69 87 81 88 67 79 91 89 89 79]
 [85 58 94 90 91 69 57 73 56 96]
 [94 75 52 95 90 82 58 86 52 78]
 [95 99 51 95 74 86 73 88 54 94]
 [68 93 88 52 73 84 68 74 84 55]]
[69.3 79.

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)