In [1]:
import numpy as np

### Basic Array Creation

# Creatation of List
How to create Lists in python?

In [1]:
li = ["Daud",6529,True]

# Type
Accuire type of list in python.

In [2]:
print(type(li))

<class 'list'>


# Creatation of Arrays
1.Simple array creation

2.Checking array "TYPE"

3.Numeric "TYPE" of array elements

4.Array dim

5.Array Shape

6.Bytes per element

7.BYTES OF MEMORY USED, How many bytes for one array element

8.Total bytes in an Array

In [74]:
# Int array
arr = np.array([2,3,4,5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.dtype

dtype('float64')

In [9]:
arr.ndim

1

In [10]:
arr.shape

(3,)

In [11]:
arr.nbytes

24

In [75]:
arr.nbytes/len(a)

8.0

In [6]:
# Decimal array
arr= np.array([2.0,3.0,4.0])

9.Try to assign a float into an int32

10.Use .fill function # fill has the same behavior


In [ ]:
# Answer here

In [83]:
a=np.array([3,4,5])
print(a.dtype)
a

int32


array([3, 4, 5])

In [87]:
a=a.astype("float")

In [88]:
a.dtype

dtype('float64')

11.Add two  arrays

12.Multiple both arrays

13.Use ** operator in array operation

14.Create array from 0.0 to 11.0

15.Multiply entire array with a scalar value
 c = (2.0 * np.pi)

16.Use np.arrange function to create an array with step of 0.5 from 1.0 to 3.0

In [12]:
a=np.array([3,4,5])
b=np.array([13,14,15])

a+b

array([16, 18, 20])

In [ ]:
a=np.array([3,4,5])
b=np.array([13,14,15])

a*b

In [13]:
a=np.array([3,4,5])
b=np.array([13,14,15])

a**b

array([  1594323, 268435456, 452807053])

In [17]:
g= np.arange(12,dtype='float')
g

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [19]:
c = (2.0 * np.pi)
c

6.283185307179586

In [90]:
c=np.arange(1.0,3.0,0.5)
c

array([1. , 1.5, 2. , 2.5])

In [95]:
np.set_printoptions(precision=1)
c

array([1. , 1.5, 2. , 2.5])

# Slicing
var[lower:upper:step]
• Extracts a portion of a sequence by specifying a lower and upper bound.

• The lower-bound element is included, but the upper-bound element is not included.

• Mathematically: [lower, upper). The step value specifies the stride between elements.

1. Etract array indices from 1 to 3:
2. Use negative indices as well
3. Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements
4. Grab last two elements
5. Grab every other element
6. slicing the last two elements returns the data there
7. Can we insert an iterable of length two? or a scalar value
8.Arrays created by slicing share data with the originating array. Changing values in a slice also changes the original array.
For example create a slice containing two elements of a changing b changed a! Have an experiment
9. if an array a = [[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]] extract values from row 3 to onward and from col 0, 2 and 5
10. Perform some masking on a = np.arange(0,36).reshape(6,6)
with mask = np.array([1, 0, 1, 0, 0, 1])


In [44]:
arr=np.array([3,4,5,6,7,8])
arr

array([3, 4, 5, 6, 7, 8])

In [45]:
arr[1:3]

array([4, 5])

In [47]:
arr[-4:-2]

array([5, 6])

In [48]:
arr[:3]

array([3, 4, 5])

In [50]:
arr[4:]

array([7, 8])

In [51]:
arr[::2]

array([3, 5, 7])

In [64]:
a = np.array([[44, 55,66,77,88],[56, 45, 243, 234, 35]])
a

array([[ 44,  55,  66,  77,  88],
       [ 56,  45, 243, 234,  35]])

In [72]:
a[1::,1::]

array([[ 45, 243, 234,  35]])

In [73]:
a[0]

array([44, 55, 66, 77, 88])

# Array Functions
1.Arange([start,] stop[, step],dtype=None)
Nearly identical to Python’s range(). Creates an array of values in the range [start,stop) with the specified step value. Allows non-integer values for start, stop, and step. Default dtype is derived from the start, stop, and step values. create an array with arange.

2.Create arrays with ONES, ZEROS, shape is a number or sequence specifying the dimensions of the array. If dtype is not specified, it defaults to float64.

3.Generate an n by n identity array. The default dtype is float64.

4.use empty, full, and fill, max, min, std, mean, var, argmax, linspace

5.

  Rule 1:
  Operations between multiple array objects are first checked for proper shape match.

  Rule 2:
  Mathematical operators (+ - * / exp, log, ...) apply element by element, on the values.

  Rule 3:
  Reduction operations (mean, std, skew, kurt, sum, prod, ...) apply to the whole array, unless an axis is specified.

  Rule 4:
  Missing values propagate unless explicitly ignored (nanmean, nansum, ...).

6.
Create the array below with
                  a = np.arange(-15, 15).reshape(5, 6) ** 2
1. The maximum of each row
2. The mean of each column
3. The position of the overall minimum


In [ ]:
# Answer Here

In [2]:
arr = np.arange(2,21,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
arr=np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arr=np.eye(4,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
arr=np.empty((4,2))
arr

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 5.53353523e-321],
       [8.70018274e-313, 0.00000000e+000]])

In [26]:
arr=np.full((4,4),fill_value=4)
arr

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [30]:
arr=np.array([3,4,5,4,3,46,8,6])
arr.max()

46

In [32]:
arr=np.array([3,4,5,4,3,46,8,6])
arr.min()

3

In [33]:
arr=np.array([3,4,5,4,3,46,8,6])
arr.std()

13.74261165135652

In [34]:
arr=np.array([3,4,5,4,3,46,8,6])
arr.mean()

9.875

In [39]:
arr=np.linspace(2,6,num=10)
arr

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [35]:
arr=np.array([3,4,5,4,3,46,8,6])
arr.argmax()

5

In [3]:
a=np.array([2,3,4,5])
b=np.array([5,6,7,8])

print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a**b)

print(np.log(a))

[ 7  9 11 13]
[-3 -3 -3 -3]
[0.4        0.5        0.57142857 0.625     ]
[10 18 28 40]
[    32    729  16384 390625]
[0.69314718 1.09861229 1.38629436 1.60943791]


In [4]:
np.nanmean(a)

3.5

In [11]:
a=np.arange(15,30)
a

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
a.shape

(15,)

In [33]:
a=a.reshape(5,3)
a

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [32]:
a[0].max()

17

In [38]:
a[:,:1].mean()

21.0

In [39]:
a[:,1:2].mean()

22.0

In [40]:
a[:,2:3].mean()

23.0

In [42]:
np.argmin(a)

0

In [43]:
np.argmax(a)

14

### Zip Operations on Numpy Arrays
Use a zip function on two arrys.

Create another array which would be the sum of corresponding elements of two arrays using for loop.

In [3]:
a = [11, 42, 23, 34]
b = [2, 3, 4, 5]

c=zip(a,b)
print(list(c))

[(11, 2), (42, 3), (23, 4), (34, 5)]


In [65]:
#For loop to add corresponding elements in two lists

# Answer Here

for i in range(len(a)):
    print(a[i]+b[i])


13
45
27
39


In [96]:
a = [11.4333, 42.345, 23.45, 34.2345]
a

[11.4333, 42.345, 23.45, 34.2345]

In [100]:
np.set_printoptions(precision=1)
a

[11.4333, 42.345, 23.45, 34.2345]